# Generated by Django 5.0.6 on 2024-08-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_description_customerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='addrees',
            new_name='address',
        ),
    ]
