# Generated by Django 5.0.6 on 2024-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_addrees_customerprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
