# Generated by Django 5.0.6 on 2024-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customerprofile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
