# Generated by Django 5.0.6 on 2024-08-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingadderss_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='adderss1',
            new_name='shipping_adderss1',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='adderss2',
            new_name='shipping_adderss2',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='country',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='email',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='full_name',
            new_name='shipping_full_name',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='state',
            new_name='shipping_state',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='user',
            new_name='shipping_user',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='zipcode',
            new_name='shipping_zipcode',
        ),
    ]
