# Generated by Django 5.0.6 on 2024-08-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_adderss1_shippingadderss_shipping_adderss1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='shipping_adderss1',
            new_name='adderss1',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='shipping_adderss2',
            new_name='adderss2',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='shipping_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='shipping_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='shipping_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='shipping_full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='shipping_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='shipping_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='shipping_zipcode',
            new_name='zipcode',
        ),
    ]
