# Generated by Django 5.0.6 on 2024-08-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_shippingadderss_adderss2_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='adderss1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='shippingadderss',
            old_name='adderss2',
            new_name='address2',
        ),
    ]
