# Generated by Django 5.0.6 on 2024-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_adderss1_shippingadderss_address1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data_ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_adderss',
            field=models.TextField(max_length=15000),
        ),
    ]
